### PR TITLE
perf: reduce GC pressure by avoiding EJSON.clone

### PR DESCRIPTION
**Pull request by alisnic**
After some loading testing efforts in our production app, we spotted in our memory profiles that EJSON.clone was one of the biggest sources of heap allocations. We started experimenting with removing some of them and see whether something breaks.

The change I submitted was tested on a e2e suite with 800+ tests and 3000+ unit tests and we didn't spot any issues so far. 

I cannot say I fully understand the implications of these changes, but from what I've seen LocalCollection from meteor core does a bunch of clones on modifications anyway, so redis-oplog does not need to clone stuff when issuing callbacks.

### CODE REVIEW

**Comment by alisnic** [comment]
cc @StorytellerCZ

**Comment by StorytellerCZ** [comment]
LGTM, but we need to get the tests going first. :disappointed:

**Comment by alisnic** [comment]
@StorytellerCZ they fail because redis oplog source has class static functions which are not supported by bundlers in old Meteor versions I assume. will try to remove 1.x from test matrix and see how 2.x tests run

can you approve workflow or maybe somehow make it so I can test changes to CI without waiting for workflow approval?

**Comment by alisnic** [comment]
@StorytellerCZ I fixed the CI. Problem was that we need to use chai version 4.x, newer versions have dependencies with static class syntax.

**Comment by alisnic** [comment]
ping @StorytellerCZ

**Comment by StorytellerCZ** [comment]
Let's see if we can run the tests on the branch.

**Comment by StorytellerCZ** [comment]
Will merge upstream and release shortly.

**Pull request merged**
